In [5]:
import numpy as np
import pandas as pd

In [4]:
a = np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
a = np.array([1,0,0],[0,1,0],[0,0,1])
print(a)

ValueError: only 2 non-keyword arguments accepted

In [7]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'

fuel_data = pd.read_csv(url,error_bad_lines = False)
fuel_data.describe(include ='all')

record_id  utility_id_ferc1   report_year  \
count                    29523      29523.000000  29523.000000   
unique                   29523               NaN           NaN   
top     f1_fuel_2005_12_70_0_1               NaN           NaN   
freq                         1               NaN           NaN   
mean                       NaN        118.601836   2005.806050   
std                        NaN         74.178353      7.025483   
min                        NaN          1.000000   1994.000000   
25%                        NaN         55.000000   2000.000000   
50%                        NaN        122.000000   2006.000000   
75%                        NaN        176.000000   2012.000000   
max                        NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [13]:
fuel_quanSK = pd.Dataframe(x).skew()[6]

AttributeError: module 'pandas' has no attribute 'Dataframe'